#!/usr/bin/python
# -*- coding: utf-8 -*-
#AEE-AMINE
#Test erreur generation

raise TypeDeLException("message à afficher")

annee = input() # L'utilisateur saisit l'année
try:
    annee = int(annee) # On tente de convertir l'année
    if annee<=0:
        raise ValueError("l'année saisie est négative ou nulle")
except ValueError:
    print("La valeur saisie est invalide (l'année est peut-être négative).")
